# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "npm" # See documentation for possible values
    open-pull-requests-limit: 10
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
    ignore: 
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]

  - package-ecosystem: "maven" # See documentation for possible values
    open-pull-requests-limit: 10
    directory: "/winery-launcher" # Location of package manifests
    schedule:
      interval: "daily"
    ignore: 
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

  - package-ecosystem: "bundler" # See documentation for possible values
    open-pull-requests-limit: 10
    directory: "/website" # Location of package manifests
    schedule:
      interval: "daily"
    ignore: 
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]
