# ----
# Site

title: TOSCA Modelling Tool
url: "https://cceh.github.io"
baseurl: "/tosca-modelling-tool"
google_analytics_key:
google_maps_javascript_api_key:
disqus_shortname:

# Values for the jekyll-seo-tag gem (https://github.com/jekyll/jekyll-seo-tag)
logo: /siteicon.png
description: A desktop distribution for the TOSCA Winery.
author:
  name: Cologne Center for eHumanities (CCeH)
  email: info-cceh@uni-koeln.de
  twitter: CCeHum
social:
  name: TOSCA Modelling Tool
  links:
    - https://github.com/cceh/tosca-modelling-tool

# -----
# Build

#timezone: Etc/UTC

#
#collections:
#  staff_members:
#    _hide_content: true

#paginate: 10
#paginate_path: "/blog/:num/"
#permalink: pretty

defaults:
#  - scope:
#      path: ""
#      type: "posts"
#    values:
#      layout: "post"
#      _options:
#        content:
#          width: 1500
#          height: 2500
#  - scope:
#      path: ""
#      type: "staff_members"
#    values:
#      _options:
#        image_path:
#          width: 600
#          height: 600
  - scope:
      path: ""
    values:
      layout: "page"
  - scope:
      path: "index.html"
    values:
      layout: "default"
#  - scope:
#      path: "contact.html"
#    values:
#      full_width: true

#jekyll-archives:
#  enabled:
#    - categories

plugins:
#  - jekyll-archives
  - jekyll-sitemap
  - jekyll-seo-tag
#  - jekyll-feed
#  - jekyll-paginate
  - jekyll-github-metadata

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE
