source 'https://rubygems.org'

gem 'jekyll', '~> 4.4.1'
gem 'dotenv'

group :jekyll_plugins do
  gem 'jekyll-archives', '~> 2.3.0'
  gem 'jekyll-feed', '~> 0.17.0'
  gem 'jekyll-paginate', '~> 1.1.0'
  gem 'jekyll-seo-tag', '~> 2.9.0'
  gem 'jekyll-sitemap', '~> 1.4.0'
  gem 'jekyll-github-metadata'
end
