source 'https://rubygems.org'

gem 'jekyll', '~> 4.2.0'
gem 'dotenv'

group :jekyll_plugins do
  gem 'jekyll-archives', '~> 2.2.1'
  gem 'jekyll-feed', '~> 0.16.0'
  gem 'jekyll-paginate', '~> 1.1.0'
  gem 'jekyll-seo-tag', '~> 2.8.0'
  gem 'jekyll-sitemap', '~> 1.4.0'
  gem 'jekyll-github-metadata'
end
