name: Push website to gh-pages branch

on:
  push:
    paths:
      - 'website/**/*'
      - '.github/workflows/gh-pages.yml'
#  workflow_call:
  workflow_run:
    workflows: [Update release data for website]
    types:
      - completed

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  push-to-gh-pages:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3

      - name: Push website directory as subtree to branch gh-pages
#        run: git push origin `git subtree split --prefix website main`:refs/heads/gh-pages --force
        run: |
          git fetch origin gh-pages:gh-pages          
          git subtree split --branch gh-pages --prefix website/
          git push origin gh-pages
