name: Push website to gh-pages branch

on:
  push:
    paths:
      - 'website/**/*'
      - '.github/workflows/gh-pages.yml'
    branches:
      - 'main'
#  workflow_call:
  release:
    types: [published, unpublished, edited]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  push-to-gh-pages:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
    env: # $BUNDLE_GEMFILE must be set at the job level, so it is set for all steps
      BUNDLE_GEMFILE: ${{ github.workspace }}/website/Gemfile

    steps:
      - uses: actions/checkout@v3

      - name: Install ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1' # Not needed with a .ruby-version file
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically

      - name: Build site
        run: |
          cd website
          bundle exec jekyll build
          cd ..

      - name: Push website directory as subtree to branch gh-pages
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -f website/_site
          git commit -m "Website build"
          git subtree split --branch gh-pages --prefix website/_site/
          git push origin gh-pages --force

